### ISSUE TITLE
Hello dude

### ISSUE THREAD

**Issue by SmithyWilliams** [jgillich/godot-snappy#14]
It feels like progress can be made on PSF but nothing that will ever go live. I feel people are wasting their time and your original work may come to nothing. THe whole community is relying on someone just like you to help. Daybreak have made aweful decisions throughout the years where they deserve to have more fan made emu projects on their doorstep

**Comment by fire** [comment]
godot-snappy is a Godot Engine addon for vertex snapping. What is the context?
