### ISSUE TITLE
Scaled MeshInstances causing issues

### ISSUE THREAD

**Issue by clemlak** [jgillich/godot-snappy#8]
Hi!
It looks like MeshInstances will cause some trouble if they are scaled. Basically the vertices will be found correctly but snapping will be a bit all over the place.

Steps to reproduce:
- Add MeshInstances to a scene
- Change the scale of (at least) one of them
- Vertices will be found correctly but snapping will misplace the meshes

**Comment by clemlak** [comment]
Just realized that the same issue happens with rotated meshes!

**Comment by jgillich** [comment]
I can reproduce with scaled objects, but snapping non-scaled rotated objects works fine for me
