### ISSUE TITLE
If the snapped object is rotated, then it the tool moves the object in the wrong direction

### ISSUE THREAD

**Issue by Frontrider** [jgillich/godot-snappy#9]
I think the video will explain it.
[snappy.webm](https://user-images.githubusercontent.com/6755034/194654999-bc4adc85-c1f9-4e8d-8d9d-b930d0a9c411.webm)

**Comment by Frontrider** [comment]
This looks like something from #8

**Comment by jgillich** [comment]
Yea the translate stuff was super weird, I have no idea what I did there. Already fixed this on the main branch a while ago. Can you test #11? Didn't test it, but it should work

**Comment by Frontrider** [comment]
[snappy2.webm](https://user-images.githubusercontent.com/6755034/194665711-0e0204b1-7e20-42e7-ae75-04ba8727dce0.webm)

**Comment by Frontrider** [comment]
Picked the wrong branch first, but yap, that fixes it.
